version: '3.9'
services:
  # Application Dockerfile in current folder
  app:
    build: .
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: employees
      DB_USER: root
      DB_PASSWORD: example

  # MySQL Database
  db:
    build: db/.
    restart: always
    ports:
      - "33060:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: employees
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-P", "3306", "-u", "root", "-pexample"]
      interval: 5s
      timeout: 5s
      retries: 20
