name: A workflow for my DevOps App
on: push

jobs:
  build:
    name: DevOps CI/CD
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up JDK 18
        uses: actions/setup-java@v4
        with:
          java-version: '18'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn package

      - name: Run docker compose
        run: docker compose up --abort-on-container-exit
